language: c 
os: linux
before_install:
  - sudo apt-get update
  - sudo apt-get -y install autotools-dev
  - sudo apt-get -y install autoconf
  - sudo apt-get -y install automake
  - sudo apt-get install -y fuse
jobs:
  include:
    - stage: build 
      script:
       - tar -xvf system1-1.0.tar.gz
       - cd ./system1-1.0
       - ./configure
       - make
